### ISSUE TITLE
General design and visual colors

### ISSUE THREAD

**Issue by caatius** [Team3-DIN21AWAP/vainamoinen#6]
General app page design from UX/UI perspective. Different test tries with different color schemes to find the default, then implement user customization in logged in state. 

This issue goes hand-in.hand with the graph interface for the visualizations.

**Comment by maaritlo** [comment]
![possibleuidesign](https://user-images.githubusercontent.com/97249642/204336708-383cfa0d-88f7-4201-81af-3a6cb39e1bf4.png)
